apiVersion: v1
kind: Secret
metadata:
  name: integrates-__DEPLOYMENT_NAME__
  namespace: ephemeral
type: Opaque
data:
  INTEGRATES_DEV_AWS_ACCESS_KEY_ID: __B64_INTEGRATES_DEV_AWS_ACCESS_KEY_ID__
  INTEGRATES_DEV_AWS_SECRET_ACCESS_KEY: __B64_INTEGRATES_DEV_AWS_SECRET_ACCESS_KEY__
  CI_COMMIT_REF_NAME: __B64_CI_COMMIT_REF_NAME__
  CI_REGISTRY_USER: ''
  CI_REGISTRY_PASSWORD: ''
