apiVersion: v1
kind: Service
metadata:
  name: service-$CI_COMMIT_REF_SLUG
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: web-$CI_COMMIT_REF_SLUG
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: review-$CI_COMMIT_REF_SLUG
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web-$CI_COMMIT_REF_SLUG
    spec:
      containers:
      - name: web
        image: registry.gitlab.com/fluidattacks/web/review:$CI_COMMIT_REF_SLUG
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: jfrog-reg
