apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdBackup"
metadata:
  name: vault-etcd-cluster-backup
spec:
  backupPolicy:
    TimeoutInSecond: 600
  clientTLSSecret: etcd-cluster-tls
  etcdEndpoints: 
    - https://etcd-cluster-client.serves.svc:2379
  storageType: S3
  s3:
    path: ${VAULT_S3_BUCKET}/vault.etcd.backup-${DATE}
    awsSecret: aws
