apiVersion: v1
kind: Secret
metadata:
  name: integrates-env
  namespace: serves
type: Opaque
data:
  AWS_ACCESS_KEY_ID: __B64_AWS_ACCESS_KEY_ID__
  AWS_SECRET_ACCESS_KEY: __B64_AWS_SECRET_ACCESS_KEY__
  JWT_TOKEN: __B64_JWT_TOKEN__
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: integrates-app
  namespace: serves
  annotations:
    kubernetes.io/change-cause: "New deployment version of async Integrates on __DATE__"
spec:
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
  template:
    metadata:
      labels:
        app: integrates-app
    spec:
      containers:
      - name: container-integrates-app
        image: registry.gitlab.com/fluidattacks/integrates/app:master
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 1500m
            memory: 3Gi
          limits:
            cpu: 3000m
            memory: 6Gi
        envFrom:
          - secretRef:
              name: integrates-env
        env:
          - name: DEPLOYMENT_DATE
            value: "__DATE__"
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        ports:
        - containerPort: 80
        readinessProbe:
          exec:
            command:
              - sh
              - -ce
              - "curl -sS http://localhost | grep 'FluidIntegrates'"
          initialDelaySeconds: 20
          periodSeconds: 5
          successThreshold: 3
          failureThreshold: 10
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                      - integrates-app
                topologyKey: "kubernetes.io/hostname"
      imagePullSecrets:
      - name: gitlab-reg
---
apiVersion: v1
kind: Service
metadata:
  name: integrates-app
  namespace: serves
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: integrates-app
