apiVersion: v1
kind: Secret
metadata:
  name: integrates-master
  namespace: production
type: Opaque
data:
  CI_COMMIT_REF_NAME: ${B64_CI_COMMIT_REF_NAME}
  CI_COMMIT_SHA: ${B64_CI_COMMIT_SHA}
  PROD_INTEGRATES_AWS_ACCESS_KEY_ID: ${B64_PROD_INTEGRATES_AWS_ACCESS_KEY_ID}
  PROD_INTEGRATES_AWS_SECRET_ACCESS_KEY: ${B64_PROD_INTEGRATES_AWS_SECRET_ACCESS_KEY}
  PRODUCT_API_TOKEN: ${B64_PRODUCT_API_TOKEN}
