---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: integrates-${CI_COMMIT_REF_NAME}
  namespace: dev
spec:
  replicas: ${REPLICAS}
  selector:
    matchLabels:
      app: integrates-${CI_COMMIT_REF_NAME}
  template:
    metadata:
      labels:
        app: integrates-${CI_COMMIT_REF_NAME}
        # This ensures that the resource is updated on every apply
        uuid: ${UUID}
    spec:
      serviceAccountName: dev
      nodeSelector:
        worker_group: dev
      containers:
        - name: back
          image: ghcr.io/fluidattacks/makes:22.11@sha256:07e6dac6271fb1ec5854f9c8b6dea48c3e7739f09c077618deeaf65691fa08f2
          imagePullPolicy: Always
          command: [sh]
          args:
            - -c
            - m gitlab:fluidattacks/universe@${CI_COMMIT_SHA} /integrates/storage/dev;
              m gitlab:fluidattacks/universe@${CI_COMMIT_SHA} /integrates/back/deploy/probes/liveness;
              m gitlab:fluidattacks/universe@${CI_COMMIT_SHA} /integrates/back/deploy/probes/readiness;
              m gitlab:fluidattacks/universe@${CI_COMMIT_SHA} /integrates/back eph
          env:
            - name: MAKES_K8S_COMPAT
              value: "1"
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://$(HOST_IP):4317"
          resources:
            requests:
              cpu: 600m
              memory: 2000Mi
            limits:
              cpu: 4000m
              memory: 5000Mi
          envFrom:
            - secretRef:
                name: integrates-${CI_COMMIT_REF_NAME}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
          ports:
            - containerPort: 8001
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - ~/.makes/out-integrates-back-deploy-probes-readiness/bin/* dev FluidIntegrates
                  http://localhost:8001
            initialDelaySeconds: 120
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 10
            timeoutSeconds: 60
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - ~/.makes/out-integrates-back-deploy-probes-liveness/bin/* dev FluidIntegrates
                  http://localhost:8001 https://${CI_COMMIT_REF_NAME}.app.fluidattacks.com
            initialDelaySeconds: 120
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 10
            timeoutSeconds: 60
        - name: db
          image: ghcr.io/fluidattacks/makes:22.11@sha256:07e6dac6271fb1ec5854f9c8b6dea48c3e7739f09c077618deeaf65691fa08f2
          imagePullPolicy: Always
          command: [m]
          args:
            - gitlab:fluidattacks/universe@${CI_COMMIT_SHA}
            - ${DB_JOB}
          env:
            - name: MAKES_K8S_COMPAT
              value: "1"
            - name: MAKES_NON_ROOT
              value: "1"
          resources:
            requests:
              cpu: 600m
              memory: 2000Mi
            limits:
              cpu: 4000m
              memory: 3000Mi
          envFrom:
            - secretRef:
                name: integrates-${CI_COMMIT_REF_NAME}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
          readinessProbe:
            tcpSocket:
              port: 28022
            initialDelaySeconds: 120
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 10
            timeoutSeconds: 60
