apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: exams
  namespace: serves
  annotations:
    kubernetes.io/change-cause: "Exams deployment from Serves on $date"
spec:
  minReadySeconds: 15
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: exams
    spec:
      containers:
      - name: container-exams
        image: registry.gitlab.com/fluidattacks/serves/exams:master
        imagePullPolicy: Always
        env:
          - name: DEPLOYMENT_DATE
            value: "$date"
        ports:
        - containerPort: 80
        readinessProbe:
          exec:
            command:
              - sh
              - -ce
              - "curl -sLS http://localhost | grep 'autonomicmind.com/courses'"
          initialDelaySeconds: 20
          periodSeconds: 5
          successThreshold: 3
          failureThreshold: 10
      imagePullSecrets:
      - name: gitlab-reg
---
apiVersion: v1
kind: Service
metadata:
  name: exams
  namespace: serves
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: exams
