closure:
  selenium: 3.14.1
  urllib3: 1.26.7
links:
  - name: selenium-3.14.1-py2.py3-none-any.whl
    sha256: 1lfwjs3am4hm6jyxnnf3p86li6nqymdx12im5siyi6c87lab3dpx
    url: https://files.pythonhosted.org/packages/b0/c9/52390baa8d6b65c3e3b89f522c3a0fcf58f2b4faf37893ef9d97cddde699/selenium-3.14.1-py2.py3-none-any.whl
  - name: selenium-3.14.1.tar.gz
    sha256: 0576jvqfwvpaap69v9pl898lj4lbdk34fjzlpkx40k0n8v82q6db
    url: https://files.pythonhosted.org/packages/75/c4/e361c5659c558edbd391d322622d8d37ae1cf011cf42470455d54956a80f/selenium-3.14.1.tar.gz
  - name: urllib3-1.26.7-py2.py3-none-any.whl
    sha256: 0i68pdi0mfnfjphp6ycsf1rzibjdzv4ipq1p6r1fbdh5jq0z9zf4
    url: https://files.pythonhosted.org/packages/af/f4/524415c0744552cce7d8bf3669af78e8a069514405ea4fcbd0cc44733744/urllib3-1.26.7-py2.py3-none-any.whl
  - name: urllib3-1.26.7.tar.gz
    sha256: 1kkf6gi8a1fs0dqkf6kpmdpsy97iirvliz8q1krxp8ppaiawd1s9
    url: https://files.pythonhosted.org/packages/80/be/3ee43b6c5757cabea19e75b8f46eaf05a2f5144107d7db48c7cf3a864f73/urllib3-1.26.7.tar.gz
python: "3.9"
