apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: integrates-master
  namespace: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: integrates-master
  minReplicas: 5
  maxReplicas: 25
  targetCPUUtilizationPercentage: 50
