apiVersion: apps/v1
kind: Deployment
metadata:
  name: integrates-${NAME}
  namespace: prod-integrates
spec:
  replicas: ${REPLICAS}
  selector:
    matchLabels:
      app: integrates-${NAME}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 10%
  template:
    metadata:
      labels:
        app: integrates-${NAME}
        # This ensures that the resource is updated on every apply
        uuid: ${UUID}
    spec:
      serviceAccountName: prod-integrates
      nodeSelector:
        worker_group: prod_integrates
      terminationGracePeriodSeconds: 60
      containers:
        - name: back
          image: ghcr.io/fluidattacks/makes:22.11@sha256:07e6dac6271fb1ec5854f9c8b6dea48c3e7739f09c077618deeaf65691fa08f2
          imagePullPolicy: Always
          command: [sh]
          args:
            - -c
            - m gitlab:fluidattacks/universe@${CI_COMMIT_SHA} /integrates/back/deploy/probes/liveness;
              m gitlab:fluidattacks/universe@${CI_COMMIT_SHA} /integrates/back/deploy/probes/readiness;
              m gitlab:fluidattacks/universe@${CI_COMMIT_SHA} /integrates/back prod
          env:
            - name: MAKES_K8S_COMPAT
              value: "1"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://adot-collector.kube-system:4317"
          resources:
            # Ensure your request and limit fits in the node:
            #   kubectl get node --selector=worker_group=prod_integrates
            #   kubectl describe node <node>
            #
            # You can have 1 pod per node, or 2, or 3, etc..
            #
            # Debug if pods were actually able to use the node:
            #   kubectl get pod -n prod-integrates
            #   kubectl describe pod -n prod-integrates <pod>
            requests:
              cpu: 1000m
              memory: 6000Mi
            limits:
              cpu: 2000m
              memory: 6500Mi
          envFrom:
            - secretRef:
                name: integrates-${NAME}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
          ports:
            - containerPort: 8001
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - ~/.makes/out-integrates-back-deploy-probes-readiness/bin/* prod_integrates
                  FluidIntegrates http://localhost:8001
            initialDelaySeconds: 120
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 10
            timeoutSeconds: 60
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - ~/.makes/out-integrates-back-deploy-probes-liveness/bin/* prod_integrates
                  FluidIntegrates http://localhost:8001 https://${ENDPOINT}.fluidattacks.com
            initialDelaySeconds: 120
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 10
            timeoutSeconds: 60
